spring:
  application:
    name: chain

  datasource:
    url: jdbc:mariadb://localhost:3306/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 100
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048

jwt:
  access-token-expiration-minutes: 10
  refresh-token-expiration-days: 7

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ap-northeast-2
    bucket: ideafestival-archive.chain
    url-prefix: https://ideafestival-archive.chain.s3.ap-northeast-2.amazonaws.com