spring:
  application:
    name: ${APP_NAME:chain}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL:false}
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048

jwt:
  access-token-expiration-minutes: ${JWT_ACCESS_EXPIRE_MIN:10}
  refresh-token-expiration-days: ${JWT_REFRESH_EXPIRE_DAYS:7}

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ap-northeast-2
    bucket: ideafestival-archive.chain
    url-prefix: https://ideafestival-archive.chain.s3.ap-northeast-2.amazonaws.com
